// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Util.proto

package com.hr.pb;

public final class Util {
  private Util() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code com.hr.pb.PBHttpState}
   */
  public enum PBHttpState
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     *成功
     * </pre>
     *
     * <code>NullError = 0;</code>
     */
    NullError(0),
    /**
     * <pre>
     *成功
     * </pre>
     *
     * <code>Success = 200;</code>
     */
    Success(200),
    /**
     * <pre>
     *失败
     * </pre>
     *
     * <code>Error = 400;</code>
     */
    Error(400),
    /**
     * <pre>
     *授权
     * </pre>
     *
     * <code>Authroize = 201;</code>
     */
    Authroize(201),
    /**
     * <pre>
     *授权失败
     * </pre>
     *
     * <code>AuthroizeFail = 202;</code>
     */
    AuthroizeFail(202),
    /**
     * <code>RuntimeException = 600;</code>
     */
    RuntimeException(600),
    /**
     * <pre>
     *存在性错误
     * </pre>
     *
     * <code>ExistError = 601;</code>
     */
    ExistError(601),
    /**
     * <pre>
     *客户端数据无法验证
     * </pre>
     *
     * <code>VaildError = 602;</code>
     */
    VaildError(602),
    UNRECOGNIZED(-1),
    ;

    /**
     * <pre>
     *成功
     * </pre>
     *
     * <code>NullError = 0;</code>
     */
    public static final int NullError_VALUE = 0;
    /**
     * <pre>
     *成功
     * </pre>
     *
     * <code>Success = 200;</code>
     */
    public static final int Success_VALUE = 200;
    /**
     * <pre>
     *失败
     * </pre>
     *
     * <code>Error = 400;</code>
     */
    public static final int Error_VALUE = 400;
    /**
     * <pre>
     *授权
     * </pre>
     *
     * <code>Authroize = 201;</code>
     */
    public static final int Authroize_VALUE = 201;
    /**
     * <pre>
     *授权失败
     * </pre>
     *
     * <code>AuthroizeFail = 202;</code>
     */
    public static final int AuthroizeFail_VALUE = 202;
    /**
     * <code>RuntimeException = 600;</code>
     */
    public static final int RuntimeException_VALUE = 600;
    /**
     * <pre>
     *存在性错误
     * </pre>
     *
     * <code>ExistError = 601;</code>
     */
    public static final int ExistError_VALUE = 601;
    /**
     * <pre>
     *客户端数据无法验证
     * </pre>
     *
     * <code>VaildError = 602;</code>
     */
    public static final int VaildError_VALUE = 602;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static PBHttpState valueOf(int value) {
      return forNumber(value);
    }

    public static PBHttpState forNumber(int value) {
      switch (value) {
        case 0: return NullError;
        case 200: return Success;
        case 400: return Error;
        case 201: return Authroize;
        case 202: return AuthroizeFail;
        case 600: return RuntimeException;
        case 601: return ExistError;
        case 602: return VaildError;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<PBHttpState>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        PBHttpState> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<PBHttpState>() {
            public PBHttpState findValueByNumber(int number) {
              return PBHttpState.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.hr.pb.Util.getDescriptor().getEnumTypes().get(0);
    }

    private static final PBHttpState[] VALUES = values();

    public static PBHttpState valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private PBHttpState(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.hr.pb.PBHttpState)
  }

  public interface PageableOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.hr.pb.Pageable)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *记录开始位置
     * </pre>
     *
     * <code>optional int32 firstResult = 1;</code>
     */
    int getFirstResult();

    /**
     * <pre>
     *查询条数
     * </pre>
     *
     * <code>optional int32 resultSize = 2;</code>
     */
    int getResultSize();

    /**
     * <pre>
     *记录总数
     * </pre>
     *
     * <code>optional int32 resultCount = 3;</code>
     */
    int getResultCount();
  }
  /**
   * Protobuf type {@code com.hr.pb.Pageable}
   */
  public  static final class Pageable extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.hr.pb.Pageable)
      PageableOrBuilder {
    // Use Pageable.newBuilder() to construct.
    private Pageable(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Pageable() {
      firstResult_ = 0;
      resultSize_ = 0;
      resultCount_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Pageable(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              firstResult_ = input.readInt32();
              break;
            }
            case 16: {

              resultSize_ = input.readInt32();
              break;
            }
            case 24: {

              resultCount_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.hr.pb.Util.internal_static_com_hr_pb_Pageable_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.hr.pb.Util.internal_static_com_hr_pb_Pageable_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.hr.pb.Util.Pageable.class, com.hr.pb.Util.Pageable.Builder.class);
    }

    public static final int FIRSTRESULT_FIELD_NUMBER = 1;
    private int firstResult_;
    /**
     * <pre>
     *记录开始位置
     * </pre>
     *
     * <code>optional int32 firstResult = 1;</code>
     */
    public int getFirstResult() {
      return firstResult_;
    }

    public static final int RESULTSIZE_FIELD_NUMBER = 2;
    private int resultSize_;
    /**
     * <pre>
     *查询条数
     * </pre>
     *
     * <code>optional int32 resultSize = 2;</code>
     */
    public int getResultSize() {
      return resultSize_;
    }

    public static final int RESULTCOUNT_FIELD_NUMBER = 3;
    private int resultCount_;
    /**
     * <pre>
     *记录总数
     * </pre>
     *
     * <code>optional int32 resultCount = 3;</code>
     */
    public int getResultCount() {
      return resultCount_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (firstResult_ != 0) {
        output.writeInt32(1, firstResult_);
      }
      if (resultSize_ != 0) {
        output.writeInt32(2, resultSize_);
      }
      if (resultCount_ != 0) {
        output.writeInt32(3, resultCount_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (firstResult_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, firstResult_);
      }
      if (resultSize_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, resultSize_);
      }
      if (resultCount_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, resultCount_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.hr.pb.Util.Pageable)) {
        return super.equals(obj);
      }
      com.hr.pb.Util.Pageable other = (com.hr.pb.Util.Pageable) obj;

      boolean result = true;
      result = result && (getFirstResult()
          == other.getFirstResult());
      result = result && (getResultSize()
          == other.getResultSize());
      result = result && (getResultCount()
          == other.getResultCount());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + FIRSTRESULT_FIELD_NUMBER;
      hash = (53 * hash) + getFirstResult();
      hash = (37 * hash) + RESULTSIZE_FIELD_NUMBER;
      hash = (53 * hash) + getResultSize();
      hash = (37 * hash) + RESULTCOUNT_FIELD_NUMBER;
      hash = (53 * hash) + getResultCount();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.hr.pb.Util.Pageable parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hr.pb.Util.Pageable parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hr.pb.Util.Pageable parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hr.pb.Util.Pageable parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hr.pb.Util.Pageable parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.hr.pb.Util.Pageable parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.hr.pb.Util.Pageable parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.hr.pb.Util.Pageable parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.hr.pb.Util.Pageable parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.hr.pb.Util.Pageable parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.hr.pb.Util.Pageable prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.hr.pb.Pageable}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.hr.pb.Pageable)
        com.hr.pb.Util.PageableOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.hr.pb.Util.internal_static_com_hr_pb_Pageable_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.hr.pb.Util.internal_static_com_hr_pb_Pageable_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.hr.pb.Util.Pageable.class, com.hr.pb.Util.Pageable.Builder.class);
      }

      // Construct using com.hr.pb.Util.Pageable.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        firstResult_ = 0;

        resultSize_ = 0;

        resultCount_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.hr.pb.Util.internal_static_com_hr_pb_Pageable_descriptor;
      }

      public com.hr.pb.Util.Pageable getDefaultInstanceForType() {
        return com.hr.pb.Util.Pageable.getDefaultInstance();
      }

      public com.hr.pb.Util.Pageable build() {
        com.hr.pb.Util.Pageable result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.hr.pb.Util.Pageable buildPartial() {
        com.hr.pb.Util.Pageable result = new com.hr.pb.Util.Pageable(this);
        result.firstResult_ = firstResult_;
        result.resultSize_ = resultSize_;
        result.resultCount_ = resultCount_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.hr.pb.Util.Pageable) {
          return mergeFrom((com.hr.pb.Util.Pageable)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.hr.pb.Util.Pageable other) {
        if (other == com.hr.pb.Util.Pageable.getDefaultInstance()) return this;
        if (other.getFirstResult() != 0) {
          setFirstResult(other.getFirstResult());
        }
        if (other.getResultSize() != 0) {
          setResultSize(other.getResultSize());
        }
        if (other.getResultCount() != 0) {
          setResultCount(other.getResultCount());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.hr.pb.Util.Pageable parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.hr.pb.Util.Pageable) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int firstResult_ ;
      /**
       * <pre>
       *记录开始位置
       * </pre>
       *
       * <code>optional int32 firstResult = 1;</code>
       */
      public int getFirstResult() {
        return firstResult_;
      }
      /**
       * <pre>
       *记录开始位置
       * </pre>
       *
       * <code>optional int32 firstResult = 1;</code>
       */
      public Builder setFirstResult(int value) {
        
        firstResult_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *记录开始位置
       * </pre>
       *
       * <code>optional int32 firstResult = 1;</code>
       */
      public Builder clearFirstResult() {
        
        firstResult_ = 0;
        onChanged();
        return this;
      }

      private int resultSize_ ;
      /**
       * <pre>
       *查询条数
       * </pre>
       *
       * <code>optional int32 resultSize = 2;</code>
       */
      public int getResultSize() {
        return resultSize_;
      }
      /**
       * <pre>
       *查询条数
       * </pre>
       *
       * <code>optional int32 resultSize = 2;</code>
       */
      public Builder setResultSize(int value) {
        
        resultSize_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *查询条数
       * </pre>
       *
       * <code>optional int32 resultSize = 2;</code>
       */
      public Builder clearResultSize() {
        
        resultSize_ = 0;
        onChanged();
        return this;
      }

      private int resultCount_ ;
      /**
       * <pre>
       *记录总数
       * </pre>
       *
       * <code>optional int32 resultCount = 3;</code>
       */
      public int getResultCount() {
        return resultCount_;
      }
      /**
       * <pre>
       *记录总数
       * </pre>
       *
       * <code>optional int32 resultCount = 3;</code>
       */
      public Builder setResultCount(int value) {
        
        resultCount_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *记录总数
       * </pre>
       *
       * <code>optional int32 resultCount = 3;</code>
       */
      public Builder clearResultCount() {
        
        resultCount_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:com.hr.pb.Pageable)
    }

    // @@protoc_insertion_point(class_scope:com.hr.pb.Pageable)
    private static final com.hr.pb.Util.Pageable DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.hr.pb.Util.Pageable();
    }

    public static com.hr.pb.Util.Pageable getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Pageable>
        PARSER = new com.google.protobuf.AbstractParser<Pageable>() {
      public Pageable parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Pageable(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Pageable> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Pageable> getParserForType() {
      return PARSER;
    }

    public com.hr.pb.Util.Pageable getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface PBErrorMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.hr.pb.PBErrorMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string value = 1;</code>
     */
    java.lang.String getValue();
    /**
     * <code>optional string value = 1;</code>
     */
    com.google.protobuf.ByteString
        getValueBytes();
  }
  /**
   * Protobuf type {@code com.hr.pb.PBErrorMessage}
   */
  public  static final class PBErrorMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.hr.pb.PBErrorMessage)
      PBErrorMessageOrBuilder {
    // Use PBErrorMessage.newBuilder() to construct.
    private PBErrorMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PBErrorMessage() {
      value_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private PBErrorMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              value_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.hr.pb.Util.internal_static_com_hr_pb_PBErrorMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.hr.pb.Util.internal_static_com_hr_pb_PBErrorMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.hr.pb.Util.PBErrorMessage.class, com.hr.pb.Util.PBErrorMessage.Builder.class);
    }

    public static final int VALUE_FIELD_NUMBER = 1;
    private volatile java.lang.Object value_;
    /**
     * <code>optional string value = 1;</code>
     */
    public java.lang.String getValue() {
      java.lang.Object ref = value_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        value_ = s;
        return s;
      }
    }
    /**
     * <code>optional string value = 1;</code>
     */
    public com.google.protobuf.ByteString
        getValueBytes() {
      java.lang.Object ref = value_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        value_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getValueBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, value_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getValueBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, value_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.hr.pb.Util.PBErrorMessage)) {
        return super.equals(obj);
      }
      com.hr.pb.Util.PBErrorMessage other = (com.hr.pb.Util.PBErrorMessage) obj;

      boolean result = true;
      result = result && getValue()
          .equals(other.getValue());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + VALUE_FIELD_NUMBER;
      hash = (53 * hash) + getValue().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.hr.pb.Util.PBErrorMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hr.pb.Util.PBErrorMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hr.pb.Util.PBErrorMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hr.pb.Util.PBErrorMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hr.pb.Util.PBErrorMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.hr.pb.Util.PBErrorMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.hr.pb.Util.PBErrorMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.hr.pb.Util.PBErrorMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.hr.pb.Util.PBErrorMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.hr.pb.Util.PBErrorMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.hr.pb.Util.PBErrorMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.hr.pb.PBErrorMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.hr.pb.PBErrorMessage)
        com.hr.pb.Util.PBErrorMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.hr.pb.Util.internal_static_com_hr_pb_PBErrorMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.hr.pb.Util.internal_static_com_hr_pb_PBErrorMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.hr.pb.Util.PBErrorMessage.class, com.hr.pb.Util.PBErrorMessage.Builder.class);
      }

      // Construct using com.hr.pb.Util.PBErrorMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        value_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.hr.pb.Util.internal_static_com_hr_pb_PBErrorMessage_descriptor;
      }

      public com.hr.pb.Util.PBErrorMessage getDefaultInstanceForType() {
        return com.hr.pb.Util.PBErrorMessage.getDefaultInstance();
      }

      public com.hr.pb.Util.PBErrorMessage build() {
        com.hr.pb.Util.PBErrorMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.hr.pb.Util.PBErrorMessage buildPartial() {
        com.hr.pb.Util.PBErrorMessage result = new com.hr.pb.Util.PBErrorMessage(this);
        result.value_ = value_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.hr.pb.Util.PBErrorMessage) {
          return mergeFrom((com.hr.pb.Util.PBErrorMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.hr.pb.Util.PBErrorMessage other) {
        if (other == com.hr.pb.Util.PBErrorMessage.getDefaultInstance()) return this;
        if (!other.getValue().isEmpty()) {
          value_ = other.value_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.hr.pb.Util.PBErrorMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.hr.pb.Util.PBErrorMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object value_ = "";
      /**
       * <code>optional string value = 1;</code>
       */
      public java.lang.String getValue() {
        java.lang.Object ref = value_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          value_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string value = 1;</code>
       */
      public com.google.protobuf.ByteString
          getValueBytes() {
        java.lang.Object ref = value_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          value_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string value = 1;</code>
       */
      public Builder setValue(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        value_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string value = 1;</code>
       */
      public Builder clearValue() {
        
        value_ = getDefaultInstance().getValue();
        onChanged();
        return this;
      }
      /**
       * <code>optional string value = 1;</code>
       */
      public Builder setValueBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        value_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:com.hr.pb.PBErrorMessage)
    }

    // @@protoc_insertion_point(class_scope:com.hr.pb.PBErrorMessage)
    private static final com.hr.pb.Util.PBErrorMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.hr.pb.Util.PBErrorMessage();
    }

    public static com.hr.pb.Util.PBErrorMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PBErrorMessage>
        PARSER = new com.google.protobuf.AbstractParser<PBErrorMessage>() {
      public PBErrorMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new PBErrorMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PBErrorMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PBErrorMessage> getParserForType() {
      return PARSER;
    }

    public com.hr.pb.Util.PBErrorMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface PBMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.hr.pb.PBMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string stringValue = 1;</code>
     */
    java.lang.String getStringValue();
    /**
     * <code>optional string stringValue = 1;</code>
     */
    com.google.protobuf.ByteString
        getStringValueBytes();

    /**
     * <code>optional int32 intValue = 2;</code>
     */
    int getIntValue();

    /**
     * <code>optional bool boolValue = 3;</code>
     */
    boolean getBoolValue();

    public com.hr.pb.Util.PBMessage.ValueCase getValueCase();
  }
  /**
   * Protobuf type {@code com.hr.pb.PBMessage}
   */
  public  static final class PBMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.hr.pb.PBMessage)
      PBMessageOrBuilder {
    // Use PBMessage.newBuilder() to construct.
    private PBMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PBMessage() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private PBMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();
              valueCase_ = 1;
              value_ = s;
              break;
            }
            case 16: {
              valueCase_ = 2;
              value_ = input.readInt32();
              break;
            }
            case 24: {
              valueCase_ = 3;
              value_ = input.readBool();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.hr.pb.Util.internal_static_com_hr_pb_PBMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.hr.pb.Util.internal_static_com_hr_pb_PBMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.hr.pb.Util.PBMessage.class, com.hr.pb.Util.PBMessage.Builder.class);
    }

    private int valueCase_ = 0;
    private java.lang.Object value_;
    public enum ValueCase
        implements com.google.protobuf.Internal.EnumLite {
      STRINGVALUE(1),
      INTVALUE(2),
      BOOLVALUE(3),
      VALUE_NOT_SET(0);
      private final int value;
      private ValueCase(int value) {
        this.value = value;
      }
      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static ValueCase valueOf(int value) {
        return forNumber(value);
      }

      public static ValueCase forNumber(int value) {
        switch (value) {
          case 1: return STRINGVALUE;
          case 2: return INTVALUE;
          case 3: return BOOLVALUE;
          case 0: return VALUE_NOT_SET;
          default: return null;
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public ValueCase
    getValueCase() {
      return ValueCase.forNumber(
          valueCase_);
    }

    public static final int STRINGVALUE_FIELD_NUMBER = 1;
    /**
     * <code>optional string stringValue = 1;</code>
     */
    public java.lang.String getStringValue() {
      java.lang.Object ref = "";
      if (valueCase_ == 1) {
        ref = value_;
      }
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (valueCase_ == 1) {
          value_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string stringValue = 1;</code>
     */
    public com.google.protobuf.ByteString
        getStringValueBytes() {
      java.lang.Object ref = "";
      if (valueCase_ == 1) {
        ref = value_;
      }
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        if (valueCase_ == 1) {
          value_ = b;
        }
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int INTVALUE_FIELD_NUMBER = 2;
    /**
     * <code>optional int32 intValue = 2;</code>
     */
    public int getIntValue() {
      if (valueCase_ == 2) {
        return (java.lang.Integer) value_;
      }
      return 0;
    }

    public static final int BOOLVALUE_FIELD_NUMBER = 3;
    /**
     * <code>optional bool boolValue = 3;</code>
     */
    public boolean getBoolValue() {
      if (valueCase_ == 3) {
        return (java.lang.Boolean) value_;
      }
      return false;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (valueCase_ == 1) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, value_);
      }
      if (valueCase_ == 2) {
        output.writeInt32(
            2, (int)((java.lang.Integer) value_));
      }
      if (valueCase_ == 3) {
        output.writeBool(
            3, (boolean)((java.lang.Boolean) value_));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (valueCase_ == 1) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, value_);
      }
      if (valueCase_ == 2) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(
              2, (int)((java.lang.Integer) value_));
      }
      if (valueCase_ == 3) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(
              3, (boolean)((java.lang.Boolean) value_));
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.hr.pb.Util.PBMessage)) {
        return super.equals(obj);
      }
      com.hr.pb.Util.PBMessage other = (com.hr.pb.Util.PBMessage) obj;

      boolean result = true;
      result = result && getValueCase().equals(
          other.getValueCase());
      if (!result) return false;
      switch (valueCase_) {
        case 1:
          result = result && getStringValue()
              .equals(other.getStringValue());
          break;
        case 2:
          result = result && (getIntValue()
              == other.getIntValue());
          break;
        case 3:
          result = result && (getBoolValue()
              == other.getBoolValue());
          break;
        case 0:
        default:
      }
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      switch (valueCase_) {
        case 1:
          hash = (37 * hash) + STRINGVALUE_FIELD_NUMBER;
          hash = (53 * hash) + getStringValue().hashCode();
          break;
        case 2:
          hash = (37 * hash) + INTVALUE_FIELD_NUMBER;
          hash = (53 * hash) + getIntValue();
          break;
        case 3:
          hash = (37 * hash) + BOOLVALUE_FIELD_NUMBER;
          hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
              getBoolValue());
          break;
        case 0:
        default:
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.hr.pb.Util.PBMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hr.pb.Util.PBMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hr.pb.Util.PBMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hr.pb.Util.PBMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hr.pb.Util.PBMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.hr.pb.Util.PBMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.hr.pb.Util.PBMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.hr.pb.Util.PBMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.hr.pb.Util.PBMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.hr.pb.Util.PBMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.hr.pb.Util.PBMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.hr.pb.PBMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.hr.pb.PBMessage)
        com.hr.pb.Util.PBMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.hr.pb.Util.internal_static_com_hr_pb_PBMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.hr.pb.Util.internal_static_com_hr_pb_PBMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.hr.pb.Util.PBMessage.class, com.hr.pb.Util.PBMessage.Builder.class);
      }

      // Construct using com.hr.pb.Util.PBMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        valueCase_ = 0;
        value_ = null;
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.hr.pb.Util.internal_static_com_hr_pb_PBMessage_descriptor;
      }

      public com.hr.pb.Util.PBMessage getDefaultInstanceForType() {
        return com.hr.pb.Util.PBMessage.getDefaultInstance();
      }

      public com.hr.pb.Util.PBMessage build() {
        com.hr.pb.Util.PBMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.hr.pb.Util.PBMessage buildPartial() {
        com.hr.pb.Util.PBMessage result = new com.hr.pb.Util.PBMessage(this);
        if (valueCase_ == 1) {
          result.value_ = value_;
        }
        if (valueCase_ == 2) {
          result.value_ = value_;
        }
        if (valueCase_ == 3) {
          result.value_ = value_;
        }
        result.valueCase_ = valueCase_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.hr.pb.Util.PBMessage) {
          return mergeFrom((com.hr.pb.Util.PBMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.hr.pb.Util.PBMessage other) {
        if (other == com.hr.pb.Util.PBMessage.getDefaultInstance()) return this;
        switch (other.getValueCase()) {
          case STRINGVALUE: {
            valueCase_ = 1;
            value_ = other.value_;
            onChanged();
            break;
          }
          case INTVALUE: {
            setIntValue(other.getIntValue());
            break;
          }
          case BOOLVALUE: {
            setBoolValue(other.getBoolValue());
            break;
          }
          case VALUE_NOT_SET: {
            break;
          }
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.hr.pb.Util.PBMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.hr.pb.Util.PBMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int valueCase_ = 0;
      private java.lang.Object value_;
      public ValueCase
          getValueCase() {
        return ValueCase.forNumber(
            valueCase_);
      }

      public Builder clearValue() {
        valueCase_ = 0;
        value_ = null;
        onChanged();
        return this;
      }


      /**
       * <code>optional string stringValue = 1;</code>
       */
      public java.lang.String getStringValue() {
        java.lang.Object ref = "";
        if (valueCase_ == 1) {
          ref = value_;
        }
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (valueCase_ == 1) {
            value_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string stringValue = 1;</code>
       */
      public com.google.protobuf.ByteString
          getStringValueBytes() {
        java.lang.Object ref = "";
        if (valueCase_ == 1) {
          ref = value_;
        }
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          if (valueCase_ == 1) {
            value_ = b;
          }
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string stringValue = 1;</code>
       */
      public Builder setStringValue(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  valueCase_ = 1;
        value_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string stringValue = 1;</code>
       */
      public Builder clearStringValue() {
        if (valueCase_ == 1) {
          valueCase_ = 0;
          value_ = null;
          onChanged();
        }
        return this;
      }
      /**
       * <code>optional string stringValue = 1;</code>
       */
      public Builder setStringValueBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        valueCase_ = 1;
        value_ = value;
        onChanged();
        return this;
      }

      /**
       * <code>optional int32 intValue = 2;</code>
       */
      public int getIntValue() {
        if (valueCase_ == 2) {
          return (java.lang.Integer) value_;
        }
        return 0;
      }
      /**
       * <code>optional int32 intValue = 2;</code>
       */
      public Builder setIntValue(int value) {
        valueCase_ = 2;
        value_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 intValue = 2;</code>
       */
      public Builder clearIntValue() {
        if (valueCase_ == 2) {
          valueCase_ = 0;
          value_ = null;
          onChanged();
        }
        return this;
      }

      /**
       * <code>optional bool boolValue = 3;</code>
       */
      public boolean getBoolValue() {
        if (valueCase_ == 3) {
          return (java.lang.Boolean) value_;
        }
        return false;
      }
      /**
       * <code>optional bool boolValue = 3;</code>
       */
      public Builder setBoolValue(boolean value) {
        valueCase_ = 3;
        value_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool boolValue = 3;</code>
       */
      public Builder clearBoolValue() {
        if (valueCase_ == 3) {
          valueCase_ = 0;
          value_ = null;
          onChanged();
        }
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:com.hr.pb.PBMessage)
    }

    // @@protoc_insertion_point(class_scope:com.hr.pb.PBMessage)
    private static final com.hr.pb.Util.PBMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.hr.pb.Util.PBMessage();
    }

    public static com.hr.pb.Util.PBMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PBMessage>
        PARSER = new com.google.protobuf.AbstractParser<PBMessage>() {
      public PBMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new PBMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PBMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PBMessage> getParserForType() {
      return PARSER;
    }

    public com.hr.pb.Util.PBMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface PBSubmitResultOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.hr.pb.PBSubmitResult)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *是否成功
     * </pre>
     *
     * <code>optional bool success = 1;</code>
     */
    boolean getSuccess();

    /**
     * <pre>
     *错误消息
     * </pre>
     *
     * <code>optional string error = 2;</code>
     */
    java.lang.String getError();
    /**
     * <pre>
     *错误消息
     * </pre>
     *
     * <code>optional string error = 2;</code>
     */
    com.google.protobuf.ByteString
        getErrorBytes();
  }
  /**
   * Protobuf type {@code com.hr.pb.PBSubmitResult}
   */
  public  static final class PBSubmitResult extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.hr.pb.PBSubmitResult)
      PBSubmitResultOrBuilder {
    // Use PBSubmitResult.newBuilder() to construct.
    private PBSubmitResult(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PBSubmitResult() {
      success_ = false;
      error_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private PBSubmitResult(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              success_ = input.readBool();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              error_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.hr.pb.Util.internal_static_com_hr_pb_PBSubmitResult_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.hr.pb.Util.internal_static_com_hr_pb_PBSubmitResult_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.hr.pb.Util.PBSubmitResult.class, com.hr.pb.Util.PBSubmitResult.Builder.class);
    }

    public static final int SUCCESS_FIELD_NUMBER = 1;
    private boolean success_;
    /**
     * <pre>
     *是否成功
     * </pre>
     *
     * <code>optional bool success = 1;</code>
     */
    public boolean getSuccess() {
      return success_;
    }

    public static final int ERROR_FIELD_NUMBER = 2;
    private volatile java.lang.Object error_;
    /**
     * <pre>
     *错误消息
     * </pre>
     *
     * <code>optional string error = 2;</code>
     */
    public java.lang.String getError() {
      java.lang.Object ref = error_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        error_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *错误消息
     * </pre>
     *
     * <code>optional string error = 2;</code>
     */
    public com.google.protobuf.ByteString
        getErrorBytes() {
      java.lang.Object ref = error_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        error_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (success_ != false) {
        output.writeBool(1, success_);
      }
      if (!getErrorBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, error_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (success_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, success_);
      }
      if (!getErrorBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, error_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.hr.pb.Util.PBSubmitResult)) {
        return super.equals(obj);
      }
      com.hr.pb.Util.PBSubmitResult other = (com.hr.pb.Util.PBSubmitResult) obj;

      boolean result = true;
      result = result && (getSuccess()
          == other.getSuccess());
      result = result && getError()
          .equals(other.getError());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + SUCCESS_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getSuccess());
      hash = (37 * hash) + ERROR_FIELD_NUMBER;
      hash = (53 * hash) + getError().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.hr.pb.Util.PBSubmitResult parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hr.pb.Util.PBSubmitResult parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hr.pb.Util.PBSubmitResult parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hr.pb.Util.PBSubmitResult parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hr.pb.Util.PBSubmitResult parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.hr.pb.Util.PBSubmitResult parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.hr.pb.Util.PBSubmitResult parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.hr.pb.Util.PBSubmitResult parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.hr.pb.Util.PBSubmitResult parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.hr.pb.Util.PBSubmitResult parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.hr.pb.Util.PBSubmitResult prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.hr.pb.PBSubmitResult}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.hr.pb.PBSubmitResult)
        com.hr.pb.Util.PBSubmitResultOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.hr.pb.Util.internal_static_com_hr_pb_PBSubmitResult_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.hr.pb.Util.internal_static_com_hr_pb_PBSubmitResult_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.hr.pb.Util.PBSubmitResult.class, com.hr.pb.Util.PBSubmitResult.Builder.class);
      }

      // Construct using com.hr.pb.Util.PBSubmitResult.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        success_ = false;

        error_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.hr.pb.Util.internal_static_com_hr_pb_PBSubmitResult_descriptor;
      }

      public com.hr.pb.Util.PBSubmitResult getDefaultInstanceForType() {
        return com.hr.pb.Util.PBSubmitResult.getDefaultInstance();
      }

      public com.hr.pb.Util.PBSubmitResult build() {
        com.hr.pb.Util.PBSubmitResult result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.hr.pb.Util.PBSubmitResult buildPartial() {
        com.hr.pb.Util.PBSubmitResult result = new com.hr.pb.Util.PBSubmitResult(this);
        result.success_ = success_;
        result.error_ = error_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.hr.pb.Util.PBSubmitResult) {
          return mergeFrom((com.hr.pb.Util.PBSubmitResult)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.hr.pb.Util.PBSubmitResult other) {
        if (other == com.hr.pb.Util.PBSubmitResult.getDefaultInstance()) return this;
        if (other.getSuccess() != false) {
          setSuccess(other.getSuccess());
        }
        if (!other.getError().isEmpty()) {
          error_ = other.error_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.hr.pb.Util.PBSubmitResult parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.hr.pb.Util.PBSubmitResult) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private boolean success_ ;
      /**
       * <pre>
       *是否成功
       * </pre>
       *
       * <code>optional bool success = 1;</code>
       */
      public boolean getSuccess() {
        return success_;
      }
      /**
       * <pre>
       *是否成功
       * </pre>
       *
       * <code>optional bool success = 1;</code>
       */
      public Builder setSuccess(boolean value) {
        
        success_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *是否成功
       * </pre>
       *
       * <code>optional bool success = 1;</code>
       */
      public Builder clearSuccess() {
        
        success_ = false;
        onChanged();
        return this;
      }

      private java.lang.Object error_ = "";
      /**
       * <pre>
       *错误消息
       * </pre>
       *
       * <code>optional string error = 2;</code>
       */
      public java.lang.String getError() {
        java.lang.Object ref = error_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          error_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *错误消息
       * </pre>
       *
       * <code>optional string error = 2;</code>
       */
      public com.google.protobuf.ByteString
          getErrorBytes() {
        java.lang.Object ref = error_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          error_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *错误消息
       * </pre>
       *
       * <code>optional string error = 2;</code>
       */
      public Builder setError(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        error_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *错误消息
       * </pre>
       *
       * <code>optional string error = 2;</code>
       */
      public Builder clearError() {
        
        error_ = getDefaultInstance().getError();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *错误消息
       * </pre>
       *
       * <code>optional string error = 2;</code>
       */
      public Builder setErrorBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        error_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:com.hr.pb.PBSubmitResult)
    }

    // @@protoc_insertion_point(class_scope:com.hr.pb.PBSubmitResult)
    private static final com.hr.pb.Util.PBSubmitResult DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.hr.pb.Util.PBSubmitResult();
    }

    public static com.hr.pb.Util.PBSubmitResult getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PBSubmitResult>
        PARSER = new com.google.protobuf.AbstractParser<PBSubmitResult>() {
      public PBSubmitResult parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new PBSubmitResult(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PBSubmitResult> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PBSubmitResult> getParserForType() {
      return PARSER;
    }

    public com.hr.pb.Util.PBSubmitResult getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_hr_pb_Pageable_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_hr_pb_Pageable_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_hr_pb_PBErrorMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_hr_pb_PBErrorMessage_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_hr_pb_PBMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_hr_pb_PBMessage_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_hr_pb_PBSubmitResult_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_hr_pb_PBSubmitResult_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nUtil.proto\022\tcom.hr.pb\"H\n\010Pageable\022\023\n\013f" +
      "irstResult\030\001 \001(\005\022\022\n\nresultSize\030\002 \001(\005\022\023\n\013" +
      "resultCount\030\003 \001(\005\"\037\n\016PBErrorMessage\022\r\n\005v" +
      "alue\030\001 \001(\t\"T\n\tPBMessage\022\025\n\013stringValue\030\001" +
      " \001(\tH\000\022\022\n\010intValue\030\002 \001(\005H\000\022\023\n\tboolValue\030" +
      "\003 \001(\010H\000B\007\n\005value\"0\n\016PBSubmitResult\022\017\n\007su" +
      "ccess\030\001 \001(\010\022\r\n\005error\030\002 \001(\t*\223\001\n\013PBHttpSta" +
      "te\022\r\n\tNullError\020\000\022\014\n\007Success\020\310\001\022\n\n\005Error" +
      "\020\220\003\022\016\n\tAuthroize\020\311\001\022\022\n\rAuthroizeFail\020\312\001\022" +
      "\025\n\020RuntimeException\020\330\004\022\017\n\nExistError\020\331\004\022",
      "\017\n\nVaildError\020\332\004B\021\n\tcom.hr.pbB\004Utilb\006pro" +
      "to3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_hr_pb_Pageable_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_hr_pb_Pageable_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_hr_pb_Pageable_descriptor,
        new java.lang.String[] { "FirstResult", "ResultSize", "ResultCount", });
    internal_static_com_hr_pb_PBErrorMessage_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_hr_pb_PBErrorMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_hr_pb_PBErrorMessage_descriptor,
        new java.lang.String[] { "Value", });
    internal_static_com_hr_pb_PBMessage_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_hr_pb_PBMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_hr_pb_PBMessage_descriptor,
        new java.lang.String[] { "StringValue", "IntValue", "BoolValue", "Value", });
    internal_static_com_hr_pb_PBSubmitResult_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_com_hr_pb_PBSubmitResult_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_hr_pb_PBSubmitResult_descriptor,
        new java.lang.String[] { "Success", "Error", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
