// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Util.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

NS_ASSUME_NONNULL_BEGIN

#pragma mark - Enum PBHttpState

typedef GPB_ENUM(PBHttpState) {
  /**
   * Value used if any message's field encounters a value that is not defined
   * by this enum. The message will also have C functions to get/set the rawValue
   * of the field.
   **/
  PBHttpState_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  /** 成功 */
  PBHttpState_NullError = 0,

  /** 成功 */
  PBHttpState_Success = 200,

  /** 失败 */
  PBHttpState_Error = 400,
  PBHttpState_RuntimeException = 600,

  /** 存在性错误 */
  PBHttpState_ExistError = 601,

  /** 客户端数据无法验证 */
  PBHttpState_VaildError = 602,
};

GPBEnumDescriptor *PBHttpState_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL PBHttpState_IsValidValue(int32_t value);

#pragma mark - UtilRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface UtilRoot : GPBRootObject
@end

#pragma mark - PBPosition

typedef GPB_ENUM(PBPosition_FieldNumber) {
  PBPosition_FieldNumber_X = 1,
  PBPosition_FieldNumber_Y = 2,
};

@interface PBPosition : GPBMessage

@property(nonatomic, readwrite) float x;

@property(nonatomic, readwrite) float y;

@end

#pragma mark - Pageable

typedef GPB_ENUM(Pageable_FieldNumber) {
  Pageable_FieldNumber_PageNumber = 1,
  Pageable_FieldNumber_PageSize = 2,
  Pageable_FieldNumber_PageCount = 3,
  Pageable_FieldNumber_ResultCount = 4,
};

@interface Pageable : GPBMessage

/** 分页开始位置 */
@property(nonatomic, readwrite) int32_t pageNumber;

/** 页尺寸 */
@property(nonatomic, readwrite) int32_t pageSize;

/** 页总数 */
@property(nonatomic, readwrite) int32_t pageCount;

/** 记录总数 */
@property(nonatomic, readwrite) int32_t resultCount;

@end

#pragma mark - PBNull

@interface PBNull : GPBMessage

@end

#pragma mark - PBReqRespMessage

typedef GPB_ENUM(PBReqRespMessage_FieldNumber) {
  PBReqRespMessage_FieldNumber_Success = 1,
  PBReqRespMessage_FieldNumber_Message = 2,
  PBReqRespMessage_FieldNumber_Type = 3,
};

@interface PBReqRespMessage : GPBMessage

@property(nonatomic, readwrite) BOOL success;

@property(nonatomic, readwrite, copy, null_resettable) NSString *message;

@property(nonatomic, readwrite) int32_t type;

@end

#pragma mark - PBErrorMessage

typedef GPB_ENUM(PBErrorMessage_FieldNumber) {
  PBErrorMessage_FieldNumber_Value = 1,
};

@interface PBErrorMessage : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *value;

@end

#pragma mark - PBMessage

typedef GPB_ENUM(PBMessage_FieldNumber) {
  PBMessage_FieldNumber_StringValue = 1,
  PBMessage_FieldNumber_IntValue = 2,
  PBMessage_FieldNumber_BoolValue = 3,
};

typedef GPB_ENUM(PBMessage_Value_OneOfCase) {
  PBMessage_Value_OneOfCase_GPBUnsetOneOfCase = 0,
  PBMessage_Value_OneOfCase_StringValue = 1,
  PBMessage_Value_OneOfCase_IntValue = 2,
  PBMessage_Value_OneOfCase_BoolValue = 3,
};

@interface PBMessage : GPBMessage

@property(nonatomic, readonly) PBMessage_Value_OneOfCase valueOneOfCase;

@property(nonatomic, readwrite, copy, null_resettable) NSString *stringValue;

@property(nonatomic, readwrite) int32_t intValue;

@property(nonatomic, readwrite) BOOL boolValue;

@end

/**
 * Clears whatever value was set for the oneof 'value'.
 **/
void PBMessage_ClearValueOneOfCase(PBMessage *message);

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
